### PR TITLE
✨ Support query events by either `sender` or `receiver` param

### PR DESCRIPTION
**Pull request by WeiJun0827**

### CODE REVIEW

**Review by williamchong — APPROVED** [review]

**Review by nnkken — COMMENTED** [review]
Why `FromAddress` and `ToAddress` instead of `Sender` and `Receiver` to align with the struct in API response?

**Comment by WeiJun0827** [comment]
> Why `FromAddress` and `ToAddress` instead of `Sender` and `Receiver` align with the struct in API response?

hmm... make sense, @williamchong  any thoughts on this?

**Comment by williamchong** [comment]
> > Why `FromAddress` and `ToAddress` instead of `Sender` and `Receiver` align with the struct in API response?
> 
> hmm... make sense, @williamchong any thoughts on this?

use sender receiver then if we don't have any existing api using fromAddress ToAddress

**Comment by WeiJun0827** [comment]
By the way, should we still need to block the requests [here](https://github.com/likecoin/likecoin-chain-tx-indexer/blob/master/rest/nft.go#L86-L89) if we want to search events based on `sender` or `receiver` but `classId` and `iscnIdPrefix` are not provided?

(related topic [here](https://www.notion.so/likecoin/All-event-list-page-for-wallet-user-6b136782fdd44641ab385f85324ae0ed))

**Comment by williamchong** [comment]
> By the way, should we still need to block the requests [here](https://github.com/likecoin/likecoin-chain-tx-indexer/blob/master/rest/nft.go#L86-L89) if we want to search events based on `sender` or `receiver` but `classId` and `iscnIdPrefix` are not provided?
> 
> (related topic [here](https://www.notion.so/likecoin/All-event-list-page-for-wallet-user-6b136782fdd44641ab385f85324ae0ed))

no, since we want an event list of all nft in our use case
good catch

**Comment by WeiJun0827** [comment]
Now supports querying by `cosmos` prefix address. Note that the address prefix of the response will be `like`. Is it OK for us?

**Review by nnkken — APPROVED** [review]

**Comment by williamchong** [comment]
> Now supports querying by `cosmos` prefix address. Note that the address prefix of the response will be `like`. Is it OK for us?

Yes like prefix is canonical

**Comment by williamchong** [comment]
Do we need index for event query though?

**Pull request merged**
