### PR TITLE
✨ Add `TotalSales` in user stats

### PR DESCRIPTION
**Pull request by WeiJun0827**

### CODE REVIEW

**Review by nnkken — APPROVED** [review]
What is the query time in your testing?

**Comment by WeiJun0827** [comment]
> What is the query time in your testing?

Usually between 4 to 8 sec 😐, probably should further optimize it?

**Comment by nnkken** [comment]
If it's joining `txs` then it will be slow, since `txs` is large (both row size and total row count).
May need to embed info in nft_event (i.e. migration...)

**Review by williamchong — COMMENTED** [review]
Can we split totalSales and totalRevenue into two PRs? Want to merge totalSales first

**Comment by WeiJun0827** [comment]
Force pushed

**Pull request merged**
